version: '3.5'



services:
  test-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: covid
      POSTGRES_PASSWORD: covid
      POSTGRES_DB: covid
    ports:
      - "8082:5432"
    volumes:
      - test_pgdata:/var/lib/postgresql/data



volumes:
  test_pgdata: