version: '3.5'



services:
  dev-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: covid
      POSTGRES_PASSWORD: covid
      POSTGRES_DB: covid
    ports:
      - "8081:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared-network
volumes:
  pgdata:

networks:
  shared-network:
    external: true